### ISSUE TITLE
setRelay not changing corrected_state from -1 when invert is false

### ISSUE THREAD

**Issue by ChuckGl** [BernhardSchlegel/BierBot-Bricks-RaspberryPi#10]
The setRelay function sets corrected_state to -1 then checks the value of "invert" for the relay.  The value of corrected_state does not get changed from -1 if the relay's invert value is false.  I think an else needs added to set corrected_state to the value of state when invert value is false. 
    if invert:
        if state == 0:
            corrected_state = 1
        else:
            corrected_state = 0
    else:                                          # ADD to change corrected_state from -1 when invert is false
        corrected_state = state

Can you explain the purpose of the invert for a relay?

ChuckGl

**Comment by BernhardSchlegel** [comment]
Hi ChuckGl,

some relays-boards a active high, some are active low. The idea was to make it configurable. But, there is certainly a bug in the software, as the else case for "if invert" is missing. Fix incoming!

Cheers,
Bernhard
