### ISSUE TITLE
Auto startup of main.py / BierBot fails

### ISSUE THREAD

**Issue by BernhardSchlegel** [BernhardSchlegel/BierBot-Bricks-RaspberryPi#6]
> Hi - yes I'm sorry to say!
> I need to manually run the main.py everytime I start the Raspberry Pi. Otherwise the Raspberry Pi doen't get activeted.

> Can't for the ... of .... understand why? You have placed an autostart in systemd - still - It doesn't work for me!
> /Fredrik W

@Wickstroem Can you provide
- bricks.log.txt after a failed startup
- systemd logs (should be `journalctl -u bierbot.service`) 

Thanks

**Comment by Wickstroem** [comment]
HEllo!
This is the LOG-file:
[Log-file.txt](https://github.com/BernhardSchlegel/BierBot-Bricks-RaspberryPi/files/9927214/Log-file.txt)

**Comment by Wickstroem** [comment]
Hi - again!
And here it is - complete(!)
[Complete log.txt](https://github.com/BernhardSchlegel/BierBot-Bricks-RaspberryPi/files/9927246/Complete.log.txt)

**Comment by BernhardSchlegel** [comment]
Thanks so much for sharing! Seems like your network is not yeat ready. Can you try the following:

Add the following line at the very top of main.py
`import time`

And then change the line 11 from
```Python
response = requests.get(url, params=post_fields)
```

to 
```Python
time.sleep(30)
response = requests.get(url, params=post_fields)
```

and restart?

This will give your WiFi 30 seconds to connect before trying to talk to the internet. You can also play with this value.

**Comment by Wickstroem** [comment]
Will do when I come home!

I won't need to open any ports?

/F

**Comment by BernhardSchlegel** [comment]
Only the standard HTTPS port is used which is always open ;) Good luck, I'll also patch the code to be more robust at startup.

**Comment by Wickstroem** [comment]
I've added the line "Import time" to main.py

I also added time.sleep(90) to linte 111 and rebooted...

So - lets see...

**Comment by Wickstroem** [comment]
Hi again!
I've put some testing into it now.

1. I installed via the commands on your front page.
2. Run them line by line.
3. After downloading from GitHub, Before **running** install command I edited two files: setup.py and main.py.
4. After editing, and saving, I ran the lines:

_sudo pip3 install -r requirements.txt
sudo python3 setup.py_

5. After Rebooting everything works!

**EDITED:**
**- main.py**
"The Raskberry Brick" wasn't recognised/found when rebooting. If I ran main.py manually after rebooting - it was found, but lost again on reboot.

**"Import time"** is already in the head of the file - didn't need to add it.
I added the "time.sleep(30)" to line 111, moved the existing rows down...

**- setup.py**
I had the problem that the Pi opened with a white screen - WEB-browser opened: "...bierbot.com/#/status" This page didn't exist so the page was white.

I removed "status" on line 112 & 114. Now the Pi opens on the home-page of bierbot. No more "white-page"

**Comment by Wickstroem** [comment]
Remaining problem
The only remaining problem is that the Brick switches between Online/Offline.

**Comment by BernhardSchlegel** [comment]
@Wickstroem if you review https://github.com/BernhardSchlegel/BierBot-Bricks-RaspberryPi/pull/8 - problems should be gone!

**Comment by BernhardSchlegel** [comment]
Stale
